const fs = require('fs');
const path = require('path');

const poolVaultPath = path.join(__dirname, '../packages/contracts/artifacts/contracts/PoolVault.sol/PoolVault.json');
const loanManagerPath = path.join(__dirname, '../packages/contracts/artifacts/contracts/LoanManager.sol/LoanManager.json');

const poolVaultArtifact = JSON.parse(fs.readFileSync(poolVaultPath, 'utf8'));
const loanManagerArtifact = JSON.parse(fs.readFileSync(loanManagerPath, 'utf8'));

const content = `// Generated by scripts/extract-abis.js

export const PoolVaultABI = ${JSON.stringify(poolVaultArtifact.abi, null, 2)} as const;
export const poolVaultAbi = PoolVaultABI;

export const LoanManagerABI = ${JSON.stringify(loanManagerArtifact.abi, null, 2)} as const;
export const loanManagerAbi = LoanManagerABI;
`;

const outputPath = path.join(__dirname, '../apps/web/src/lib/onchain/abis.ts');
fs.writeFileSync(outputPath, content);
console.log('ABIs extracted to ' + outputPath);
